### ISSUE TITLE
undefined is not an object error

### ISSUE THREAD

**Issue by rakesh0910** [dailydrip/react-native-navigation-sample#1]
I had tried out your code in react-native to get an idea about react-navigation, but I get below error :

<img width="376" alt="screen shot 2017-03-28 at 4 53 32 pm" src="https://cloud.githubusercontent.com/assets/26722866/24402480/6f71d0ee-13d6-11e7-86f4-370367d2f2d3.png">

Can you please help me resolve the issue. Thanks in advance

**Comment by Rizwanilahi** [comment]
@rakesh0910 Share your code please

**Comment by sushant6309** [comment]
@rakesh0910 Hi I also got the same error.

const Routes = StackNavigator({
	Home: { screen: App },
	Chat: { screen: SecondScreen },
});

AppRegistry.registerComponent('Ace', () => Ace);

Mistake I was making was I was passing the class to the AppRegistry but instead we have to pass the Routes.

**Comment by franzejr** [comment]
Yes. I checked right now and everything is fine. :)
